name: EventHub

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  runtime_config:
    name: Read runtime config
    runs-on: ubuntu-latest
    outputs:
      lab: ${{ steps.read.outputs.lab }}
    steps:
      - uses: actions/checkout@v4
      - name: Read lab number
        id: read
        run: |
          LAB=$(.github/scripts/lab_number.sh)
          echo "lab=$LAB" >> $GITHUB_OUTPUT

  lab1:
    needs: runtime_config
    if: ${{ needs.runtime_config.outputs.lab >= 1 }}
    uses: sitnikovik/ndbx/.github/workflows/reusable_eventhub_lab1.yml@main
    with:
      scripts_dir: ".github/scripts"
      lab_check_dir: "autograder/cmd/lab1"

  lab2:
    needs: runtime_config
    if: ${{ needs.runtime_config.outputs.lab >= 2 }}
    uses: sitnikovik/ndbx/.github/workflows/reusable_eventhub_lab2.yml@main
    with:
      scripts_dir: ".github/scripts"
      lab_check_dir: "autograder/cmd/lab2"

  lab3:
    needs: runtime_config
    if: ${{ needs.runtime_config.outputs.lab >= 3 }}
    uses: sitnikovik/ndbx/.github/workflows/reusable_eventhub_lab3.yml@main
    with:
      scripts_dir: ".github/scripts"
      lab_check_dir: "autograder/cmd/lab3"

  lab4:
    needs: runtime_config
    if: ${{ needs.runtime_config.outputs.lab >= 4 }}
    uses: sitnikovik/ndbx/.github/workflows/reusable_eventhub_lab4.yml@main
    with:
      scripts_dir: ".github/scripts"
      lab_check_dir: "autograder/cmd/lab4"